const ADD_POST = "ADD_POST";
const EDIT_POST = "EDIT_POST";
const DELETE_POST = "DELETE_POST";
const ADD_COMMENT = "ADD_COMMENT";
const DELETE_COMMENT = "DELETE_COMMENT";

export { ADD_POST, EDIT_POST, DELETE_POST, ADD_COMMENT, DELETE_COMMENT };
